export const serverUrl = "http://10.0.2.2:8000"; //address taken from here https://stackoverflow.com/questions/38418998/react-native-fetch-network-request-failed

export const LATITUDE_DELTA = 0.001;

export const LONGITUDE_DELTA = 0.001;

export const MAX_IMAGE_COUNT = 4;

export const MAX_IMAGE_WIDTH_OR_HEIGHT = 500; // in pixels

export const CATEGORIES = {
  lighting: { label: "Oświetlenie", value: "Lighting" },
  plumbing: { label: "Hydraulika", value: "Plumbing" },
  electrical_equipment: {
    label: "Wyposażenie elektryczne",
    value: "Electrical_equipment",
  },
  furnishings: { label: "Wyposażenie meblowe", value: "Furnishings" },
  electrical_system: {
    label: "Instalacja elektryczna",
    value: "Electrical_system",
  },
  construction_repairs: {
    label: "Naprawy budownicze",
    value: "Construction_repairs",
  },
  untidiness: { label: "Nieporządek", value: "Untidiness" },
  doors_and_windows: { label: "Drzwi i okna", value: "Doors_and_windows" },
  supplies: { label: "Zaopatrzenie", value: "Supplies" },
};

export const CATEGORY_TO_TAGS = {
  lighting: [
    "lighting",
    "light",
    "light fixture",
    "lamp",
    "lightbox",
    "fluorescent lamp",
    "spotlight",
    "headlight",
    "lantern",
  ],
  plumbing: [
    "bathroom",
    "toilet",
    "toliet seat",
    "bidet",
    "bathroom accessory",
    "urinal",
    "tap",
    "faucet",
    "pipe",
    "washbasin",
    "basin",
    "sink",
    "leak",
    "water",
    "radiator",
    "plumbing",
    "drain",
    "plumbing fixture",
  ],
  electrical_equipment: [
    "projector",
    "computer",
    "keyboard",
    "mouse",
    "computer mouse",
    "cable",
    "wire",
    "vending machine",
    "espresso machine",
    "coffeemaker",
    "fridge",
    "microwave",
    "kettle",
    "speaker",
    "loudspeaker",
    "microphone",
    "laptop",
    "monitor",
    "display",
    "remote control",
    "input device",
    "output device",
    "electronic device",
    "peripheral",
    "printer",
    "photocopier",
    "air conditioner",
    "fan",
    "machine",
    "camera",
    "refrigerator",
  ],
  furnishings: [
    "chair",
    "swivel chair",
    "office chair",
    "whiteboard",
    "table",
    "desk",
    "bench",
    "backrest",
    "cabinet",
    "closet",
    "cupboard",
    "shelf",
    "furniture",
    "mirror",
    "drinker",
    "waste container",
    "street furniture",
    "seat",
    "bin",
    "recycle bin",
    "armchair",
  ],
  electrical_system: [
    "electrical box",
    "socket",
    "power socket",
    "light switch",
    "switch",
    "cables",
    "wires",
  ],
  construction_repairs: [
    "hole in the wall",
    "wall",
    "ceiling",
    "crack",
    "leak",
    "brick",
    "drywall",
    "plaster",
    "floor",
    "tile",
    "plaster",
    "vent",
    "elevator",
    "pole",
    "manhole",
    "sidewalk",
    "concrete",
    "curb",
  ],
  untidiness: [
    "dirt",
    "puddle",
    "fudge",
    "stain",
    "garbage",
    "junk",
    "trash",
    "mess",
    "ford",
    "mud",
    "fecal matter",
    "litter",
  ],
  doors_and_windows: [
    "door",
    "window",
    "lock",
    "handle",
    "door handle",
    "windshield",
    "hinge",
    "latch",
  ],
  supplies: [
    "toilet paper",
    "fire extinguisher",
    "extinguisher",
    "paper",
    "soap",
    "soapbox",
    "disinfectant",
    "paper towel",
    "bathroom accessory",
  ],
};

export const CATEGORY_TO_ICON = {
  Lighting: "lightbulb-on",
  Plumbing: "water-pump",
  Electrical_equipment: "desktop-classic",
  Furnishings: "table-chair",
  Electrical_system: "lightning-bolt",
  Construction_repairs: "hammer-screwdriver",
  Untidiness: "broom",
  Doors_and_windows: "door",
  Supplies: "paperclip",
};

//Azure cognitive services constants
export const key = "1306ad78a86a41c18ff997af89080f03";
const endpointTagsPl =
  "https://westeurope.api.cognitive.microsoft.com/vision/v3.2/analyze?visualFeatures=Tags&language=pl";
export const cognitiveServicesBaseUrl =
  "https://westeurope.api.cognitive.microsoft.com/vision/v3.2";
export const endpointTagsEn = "/analyze?visualFeatures=Tags";
