export const CATEGORY_TO_TAGS = {
  lighting: [
    "lighting",
    "light",
    "light fixture",
    "lamp",
    "lightbox",
    "fluorescent lamp",
    "spotlight",
    "headlight",
    "lantern",
    "lighting accessory", //
    "street light", //
  ],
  plumbing: [
    "toilet",
    "toliet seat",
    "bidet",
    "urinal",
    "tap",
    "faucet",
    "pipe",
    "washbasin",
    "basin",
    "sink",
    "leak",
    //"water",
    "radiator",
    "plumbing",
    "drain",
    "plumbing fixture",
    "drinker",
    "bathroom sink", //
    "plumbing fitting", //
  ],
  electrical_equipment: [
    "projector",
    "computer",
    "keyboard",
    "mouse",
    "computer mouse",
    "wire",
    "vending machine",
    "espresso machine",
    "coffeemaker",
    "fridge",
    "microwave",
    "kettle",
    "speaker",
    "loudspeaker",
    "microphone",
    "laptop",
    "monitor",
    "display",
    "remote control",
    "input device",
    "output device",
    "electronic device",
    "peripheral",
    "printer",
    "photocopier",
    "air conditioner",
    "fan",
    //"machine",
    "camera",
    "refrigerator",
    "hand dryer",
    "surveillance camera", //
    "audio equipment", //
  ],
  untidiness: [
    "dirt",
    "dirty",
    "puddle",
    "fudge",
    "stain",
    "garbage",
    "junk",
    "trash",
    "mess",
    "ford",
    "mud",
    "fecal matter",
    "litter",
    "pollution", //
    "waste", //
  ],
  furnishings: [
    "chair",
    "swivel chair",
    "office chair",
    "whiteboard",
    "blackboard",
    "table",
    "desk",
    "bench",
    "outdoor bench",
    "backrest",
    "cabinet",
    "closet",
    "cupboard",
    "shelf",
    "furniture",
    "mirror",
    //"waste container",
    "furniture",
    "seat",
    "bin",
    //"recycle bin",
    "armchair",
    "exercise equipment",
    "outdoor furniture", //
    "outdoor table", //
  ],
  electrical_system: [
    "electrical box",
    "socket",
    "power socket",
    "light switch",
    "switch",
    "cable",
    "cables",
    "wires",
    "elevator",
    "power plugs and sockets",
    //"electricity", //
    "electrical_supply", //
    "electrical wiring", //
    "fire alarm system", //
    "wire", //
  ],
  construction_repairs: [
    "hole in the wall",
    "crack",
    "leak",
    "drywall",
    "plaster",
    "tile",
    "plaster",
    "vent",
    "pole",
    "manhole",
    "barricade",
  ],
  doors_and_windows: [
    "door",
    "window",
    "lock",
    "handle",
    "door handle",
    "windshield",
    "hinge",
    "latch",
    "doorframe",
    "frame",
    "hinges",
    "home door", //
    "sash window", //
  ],
  supplies: [
    "toilet paper",
    "fire extinguisher",
    "extinguisher",
    //"paper",
    "soap",
    "soapbox",
    "disinfectant",
    "paper towel",
    "bathroom accessory",
    "soap dispenser",
    "dispenser",
    "tiolet roll holder",
    "paper towel holder", //
  ],
};

export const CATEGORY_TO_TAGS_TO_CHECK_LAST = {
  construction_repairs: [
    "brick",
    // "wall",
    // "floor",
    // "ceiling",
    //"sidewalk",
    //"concrete",
    "curb",
    //"building material",
  ],
  plumbing: ["bathroom", "bathroom accessory"],
  furnishings: ["waste container", "recycle bin"],
};

export const CATEGORY_TO_TAGS_FULL = {
  lighting: [
    "lighting",
    "light",
    "light fixture",
    "lamp",
    "lightbox",
    "fluorescent lamp",
    "spotlight",
    "headlight",
    "lantern",
    "lighting accessory", //
    "street light", //
  ],
  plumbing: [
    "toilet",
    "toliet seat",
    "bidet",
    "urinal",
    "tap",
    "faucet",
    "pipe",
    "washbasin",
    "basin",
    "sink",
    "leak",
    //"water",
    "radiator",
    "plumbing",
    "drain",
    "plumbing fixture",
    "drinker",
    "bathroom",
    "bathroom accessory",
    "bathroom sink", //
    "plumbing fitting", //
  ],
  electrical_equipment: [
    "projector",
    "computer",
    "keyboard",
    "mouse",
    "computer mouse",
    "wire",
    "vending machine",
    "espresso machine",
    "coffeemaker",
    "fridge",
    "microwave",
    "kettle",
    "speaker",
    "loudspeaker",
    "microphone",
    "laptop",
    "monitor",
    "display",
    "remote control",
    "input device",
    "output device",
    "electronic device",
    "peripheral",
    "printer",
    "photocopier",
    "air conditioner",
    "fan",
    //"machine",
    "camera",
    "refrigerator",
    "hand dryer",
    "surveillance camera", //
    "audio equipment", //
  ],
  furnishings: [
    "chair",
    "swivel chair",
    "office chair",
    "whiteboard",
    "blackboard",
    "table",
    "desk",
    "bench",
    "outdoor bench",
    "backrest",
    "cabinet",
    "closet",
    "cupboard",
    "shelf",
    "furniture",
    "mirror",
    "waste container",
    "furniture",
    "seat",
    "bin",
    "recycle bin",
    "armchair",
    "exercise equipment",
    "outdoor furniture", //
    "outdoor table", //
  ],
  electrical_system: [
    "electrical box",
    "socket",
    "power socket",
    "light switch",
    "switch",
    "cable",
    "cables",
    "wires",
    "wire", //
    "elevator",
    "power plugs and sockets",
    // "electricity", //
    "electrical_supply", //
    "electrical wiring", //
    "fire alarm system", //
  ],
  construction_repairs: [
    "hole in the wall",
    "crack",
    "leak",
    "drywall",
    "plaster",
    "tile",
    "plaster",
    "vent",
    "pole",
    "manhole",
    "barricade",
    "brick",
    //"wall",
    //"floor",
    //"ceiling",
    //"sidewalk",
    //"concrete",
    "curb",
  ],
  untidiness: [
    "dirt",
    "dirty",
    "puddle",
    "fudge",
    "stain",
    "garbage",
    "junk",
    "trash",
    "mess",
    "ford",
    "mud",
    "fecal matter",
    "litter",
    "waste container",
    "pollution", //
    "waste", //
  ],
  doors_and_windows: [
    "door",
    "window",
    "lock",
    "handle",
    "door handle",
    "windshield",
    "hinge",
    "latch",
    "doorframe",
    "frame",
    "hinges",
    "home door", //
    "sash window", //
  ],
  supplies: [
    "toilet paper",
    "fire extinguisher",
    "extinguisher",
    // "paper",
    "soap",
    "soapbox",
    "disinfectant",
    "paper towel",
    "bathroom accessory",
    "soap dispenser",
    "dispenser",
    "tiolet roll holder",
    "paper towel holder", //
  ],
};
